
all: build clean

build:
	/usr/bin/pdflatex Group4Project5.tex

clean:
	mv Group4Project5.aux tmp/
	mv Group4Project5.log tmp/
	mv Group4Project5.lot tmp/
	mv Group4Project5.toc tmp/
	mv Group4Project5.lof tmp/
	mv texput.log tmp/

# DO NOT DELETE
